import { ICurrentW } from './types/entityTypes';

// Наименование цветовой темы
export const themeName = {
    dark: 'Dark',
    light: 'Light',
};

// Плейсхолдеры для инпутов
export const placeholders = {
    search: 'Search location...',
};

// Пустой объект погоды
export const initialCurrentWeather: ICurrentW = {
    dt: {
        currentDate: '',
        currentTime: '',
        dayWeek: '',
    },

    country: '',
    city: '',
    timezone: 0,

    temp: 0,
    feelsLike: 0,
    tempMin: 0,
    tempMax: 0,
    pressure: 0,
    humidity: 0,
    clouds: 0,
    visibility: 0,
    sunrise: 0,
    sunset: 0,
    weather: {
        id: 0,
        main: '',
        description: '',
        icon: '',
    },
    wind: {
        speed: 0,
        deg: 0,
        gust: 0,
    },
};

// Иконки
export const icons: { [key: string]: string } = {
    '01d': 'clearDay',
    '02d': '',
    '03d': '',
    '04d': '',
    '09d': '',
    '10d': '',
    '11d': '',
    '13d': '',
    '50d': '',
    '01n': '',
    '02n': '',
    '03n': '',
    '04n': '',
    '09n': '',
    '10n': '',
    '11n': '',
    '13n': '',
    '50n': 'clearNight',
};

// Страны
export const countries: { [key: string]: string } = {
    AU: 'Australia',
    AT: 'Austria',
    AZ: 'Azerbaijan',
    AL: 'Albania',
    DZ: 'Algeria',
    VI: 'United States Virgin Islands',
    AS: 'American Samoa',
    AI: 'Anguilla',
    AO: 'Angola',
    AD: 'Andorra',
    AQ: 'Antarctica',
    AG: 'Antigua and Barbuda',
    AR: 'Argentina',
    AM: 'Armenia',
    AW: 'Aruba',
    AF: 'Afghanistan',
    BS: 'Bahamas',
    BD: 'Bangladesh',
    BB: 'Barbados',
    BH: 'Bahrain',
    BZ: 'Belize',
    BY: 'Belarus',
    BE: 'Belgium',
    BJ: 'Benin',
    BM: 'Bermuda',
    BG: 'Bulgaria',
    BO: 'Bolivia',
    BQ: 'Caribbean Netherlands',
    BA: 'Bosnia and Herzegovina',
    BW: 'Botswana',
    BR: 'Brazil',
    IO: 'British Indian Ocean Territory',
    VG: 'British Virgin Islands',
    BN: 'Brunei Darussalam',
    BV: 'Bouvet Island',
    BF: 'Burkina Faso',
    BI: 'Burundi',
    BT: 'Bhutan',
    VU: 'Vanuatu',
    VA: 'Vatican',
    GB: 'Great Britain',
    HU: 'Hungary',
    VE: 'Venezuela',
    TL: 'East Timor',
    VN: 'Vietnam',
    GA: 'Gabon',
    HT: 'Haiti',
    GY: 'Guyana',
    GM: 'Gambia',
    GH: 'Ghana',
    GP: 'Guadeloupe',
    GT: 'Guatemala',
    GN: 'Guinea',
    GW: 'Guinea-Bissau',
    DE: 'Germany',
    GG: 'Guernsey',
    GI: 'Gibraltar',
    HN: 'Honduras',
    HK: 'Hong Kong',
    GD: 'Grenada',
    GL: 'Greenland',
    GR: 'Greece',
    GE: 'Georgia',
    GU: 'Guam',
    DK: 'Denmark',
    CD: 'Democratic Republic of the Congo',
    JE: 'Jersey',
    DJ: 'Djibouti',
    DM: 'Dominica',
    DO: 'Dominican Republic',
    EG: 'Egypt',
    ZM: 'Zambia',
    EH: 'Western Sahara',
    ZW: 'Zimbabwe',
    IL: 'Israel',
    IN: 'India',
    ID: 'Indonesia',
    JO: 'Jordan',
    IQ: 'Iraq',
    IR: 'Iran',
    IE: 'Ireland',
    IS: 'Iceland',
    ES: 'Spain',
    IT: 'Italy',
    YE: 'Yemen',
    CV: 'Cape Verde',
    KZ: 'Kazakhstan',
    KY: 'Cayman Islands',
    KH: 'Cambodia',
    CM: 'Cameroon',
    CA: 'Canada',
    QA: 'Quatar',
    KE: 'Kenya',
    CY: 'Cyprus',
    KG: 'Kyrgyzstan',
    KI: 'Kiribati',
    CN: 'China',
    KP: 'North Korea',
    CC: 'Cocos (Keeling) Islands',
    CO: 'Colombia',
    KM: 'Comoros',
    KR: 'Korea',
    CR: 'Costa Rica',
    CI: 'Cote d`Ivoire (Ivory Coast)',
    CU: 'Cuba',
    KW: 'Kuwait',
    CW: 'Curacao',
    LA: 'Laos',
    LV: 'Latvia',
    LS: 'Lesotho',
    LR: 'Liberia',
    LB: 'Lebanon',
    LY: 'Libya',
    LT: 'Lithuania',
    LI: 'Liechtenstein',
    LU: 'Luxembourg',
    MU: 'Mauritius',
    MR: 'Mauritania',
    MG: 'Madagascar',
    YT: 'Mayotte',
    MO: 'Macau',
    MK: 'Macedonia',
    MW: 'Malawi',
    MY: 'Malaysia',
    ML: 'Mali',
    MV: 'Maldives',
    MT: 'Malta',
    MA: 'Morocco',
    MQ: 'Martinique',
    MH: 'Marshall Islands',
    MX: 'Mexico',
    MZ: 'Mozambique',
    MD: 'Moldova',
    MC: 'Monaco',
    MN: 'Mongolia',
    MS: 'Montserrat',
    MM: 'Myanmar (Burma)',
    NA: 'Namibia',
    NR: 'Nauru',
    NP: 'Nepal',
    NE: 'Niger',
    NG: 'Nigeria',
    AN: 'Netherlands Antilles',
    NL: 'Netherlands',
    NI: 'Nicaragua',
    NU: 'Niue',
    NZ: 'New Zealand',
    NC: 'New Caledonia',
    NO: 'Norway',
    AE: 'United Arab Emirates',
    OM: 'Oman',
    NF: 'Norfolk Island',
    CX: 'Christmas Island',
    SH: 'Saint Helena',
    HM: 'Heard Island and McDonald Islands',
    CK: 'Cook Islands',
    PN: 'Pitcairn Islands',
    TC: 'The Turks and Caicos Islands',
    WF: 'Wallis and Futuna',
    PK: 'Pakistan',
    PW: 'Palau',
    PS: 'Palestinian Territories',
    PA: 'Panama',
    PG: 'Papua New Guinea',
    PY: 'Paraguay',
    PE: 'Peru',
    PL: 'Poland',
    PT: 'Portugal',
    PR: 'Puerto Rico',
    CG: 'Republic of the Congo',
    RE: 'Reunion',
    RU: 'Russia',
    RW: 'Rwanda',
    RO: 'Romania',
    SV: 'El Salvador',
    WS: 'Samoa',
    SM: 'San Marino',
    ST: 'Sao Tome and Principe',
    SA: 'Saudi Arabia',
    MP: 'Northern Mariana Islands',
    SC: 'Seychelles',
    PM: 'Saint-Pierre and Miquelon',
    SN: 'Senegal',
    VC: 'Saint Vincent and the Grenadines',
    KN: 'Saint Kitts and Nevis',
    LC: 'Saint Lucia',
    RS: 'Serbia',
    SG: 'Singapore',
    SY: 'Syria',
    SK: 'Slovakia',
    SI: 'Slovenia',
    SB: 'Solomon Islands',
    SO: 'Somalia',
    SD: 'Sudan',
    SR: 'Suriname',
    US: 'USA',
    SL: 'Sierra Leone',
    TJ: 'Tajikistan',
    TH: 'Thailand',
    TW: 'Taiwan (Taipei)',
    TZ: 'Tanzania',
    TG: 'Togo',
    TK: 'Tokelau',
    TO: 'Tonga',
    TT: 'Trinidad and Tobago',
    TV: 'Tuvalu',
    TN: 'Tunisia',
    TM: 'Turkmenistan',
    TR: 'Turkey',
    UG: 'Uganda',
    UZ: 'Uzbekistan',
    UA: 'Ukraine',
    UY: 'Uruguay',
    FO: 'Faroe Islands',
    FM: 'Federated States of Micronesia',
    FJ: 'Fiji',
    PH: 'Philippines',
    FI: 'Finland',
    FK: 'Falkland Islands (Malvinas)',
    FR: 'France',
    GF: 'French Guiana',
    PF: 'French Polynesia',
    TF: 'French Southern Territories',
    HR: 'Croatia',
    CF: 'Central African Republic',
    TD: 'Chad',
    ME: 'Montenegro',
    CZ: 'Czechia',
    CL: 'Chile',
    CH: 'Switzerland',
    SE: 'Sweden',
    SJ: 'Svalbard and Jan Mayen',
    LK: 'Sri Lanka',
    EC: 'Ecuador',
    GQ: 'Equatorial Guinea',
    ER: 'Eritrea',
    SZ: 'Eswatini',
    EE: 'Estonia',
    ET: 'Ethiopia',
    ZA: 'Republic of South Africa',
    GS: 'South Georgia and the South Sandwich Islands',
    JM: 'Jamaica',
    JP: 'Japan',
};
